[package]
name = "jscjs-sys"
version = "0.0.1"
authors = ["bynx <drtychai@protonmail.com>"]
description = "System crate for the Webkit JavsScript engine: JavaScriptCore"
repository = "https://github.com/drtychai/jsc-sys"
edition = "2018"
build = "build.rs"
license = "MPL-2.0"
include = [ "jsc-defs_*/**", "WebKit/WebKitBuild/Debug/JavaScriptCore/**" ]

[lib]
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
libc = "0.2.76"

[build-dependencies]
bindgen = "0.55.1"
