[package]
name = "jscjs-sys"
version = "0.0.2"
authors = ["bynx <drtychai@protonmail.com>"]
description = "System crate for the Webkit JavsScript engine: JavaScriptCore"
repository = "https://github.com/drtychai/jsc-sys"
build = "build.rs"
license = "MPL-2.0"
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.76"

[build-dependencies]
bindgen = "0.55.1"
