[package]
name = "jscjs_sys"
version = "0.0.1"
authors = ["bynx <drtychai@protonmail.com>"]
description = "System crate for the Webkit JavaScriptCore JavaScript engine."
repository = "https://github.com/drtychai/jsc-sys"
edition = "2018"
build = "build.rs"
license = "MPL-2.0"
include = [ "jsc-defs_*/**", "WebKit/WebKitBuild/Debug/JavaScriptCore/**" ]

[lib]
name = "jscjs_sys"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
libc = "0.2.76"

[build-dependencies]
bindgen = "*"
pkg-config = "0.3.14"
walkdir = "2.3.1"
