[package]
name = "jscjs_sys"
description = "System crate providing bindings to the Webkit JavsScript engine, JavaScriptCore"
repository = "https://github.com/drtychai/jsc-sys"
version = "0.0.2"
authors = ["bynx <drtychai@protonmail.com>"]
links = "jscjs"
build = "build.rs"
license = "AGPL-3.0"
edition = "2018"
exclude = [
    "*.lock",
    "**/WebKit",
    "**/*.yml",
]

[dependencies]
url = "*"
libc = "0.2.76"

[build-dependencies]
pkg-config = "*"
bindgen = "0.55.1"
