[package]
name = "jscjs_sys"
description = "System crate providing bindings to the Webkit JavsScript engine, JavaScriptCore"
repository = "https://github.com/drtychai/jsc-sys"
version = "0.0.3"
authors = ["bynx <drtychai@protonmail.com>"]
links = "glib-2.0"
build = "build.rs"
license = "AGPL-3.0"
edition = "2018"
exclude = [
    "*.lock",
    "**/WebKit",
    "**/*.yml",
]

[dependencies]
url = "2.1.1"
libc = "0.2.76"

[build-dependencies]
pkg-config = "0.3.18"
bindgen = "0.55.1"
