var N = null;var sourcesIndex = {};
sourcesIndex["cxx"] = {"name":"","dirs":[{"name":"macros","files":["assert.rs","concat.rs","mod.rs"]},{"name":"symbols","files":["exception.rs","mod.rs","rust_slice.rs","rust_str.rs","rust_string.rs","rust_vec.rs"]}],"files":["cxx_string.rs","cxx_vector.rs","exception.rs","extern_type.rs","fmt.rs","function.rs","lib.rs","memory.rs","opaque.rs","result.rs","rust_slice.rs","rust_str.rs","rust_string.rs","rust_type.rs","rust_vec.rs","shared_ptr.rs","type_id.rs","unique_ptr.rs","unwind.rs","vector.rs","weak_ptr.rs"]};
sourcesIndex["cxxbridge_macro"] = {"name":"","dirs":[{"name":"syntax","files":["atom.rs","attrs.rs","check.rs","derive.rs","discriminant.rs","doc.rs","error.rs","file.rs","ident.rs","impls.rs","improper.rs","instantiate.rs","mangle.rs","map.rs","mod.rs","names.rs","namespace.rs","parse.rs","pod.rs","qualified.rs","report.rs","resolve.rs","set.rs","symbol.rs","tokens.rs","toposort.rs","trivial.rs","types.rs","visit.rs"]}],"files":["derive.rs","expand.rs","generics.rs","lib.rs","type_id.rs"]};
sourcesIndex["form_urlencoded"] = {"name":"","files":["lib.rs"]};
sourcesIndex["idna"] = {"name":"","files":["lib.rs","punycode.rs","uts46.rs"]};
sourcesIndex["jscjs_sys"] = {"name":"","dirs":[{"name":"runtime","files":["mod.rs","type_system.rs"]}],"files":["api.rs","lib.rs"]};
sourcesIndex["link_cplusplus"] = {"name":"","files":["lib.rs"]};
sourcesIndex["matches"] = {"name":"","files":["lib.rs"]};
sourcesIndex["percent_encoding"] = {"name":"","files":["lib.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","files":["detection.rs","fallback.rs","lib.rs","marker.rs","parse.rs","wrapper.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","files":["clone.rs","gen_helper.rs"]}],"files":["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","file.rs","generics.rs","group.rs","ident.rs","item.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","pat.rs","path.rs","print.rs","punctuated.rs","reserved.rs","sealed.rs","span.rs","spanned.rs","stmt.rs","thread.rs","token.rs","ty.rs","verbatim.rs","whitespace.rs"]};
sourcesIndex["tinyvec"] = {"name":"","dirs":[{"name":"array","files":["generated_impl.rs"]}],"files":["array.rs","arrayvec.rs","arrayvec_drain.rs","lib.rs","slicevec.rs","tinyvec.rs"]};
sourcesIndex["tinyvec_macros"] = {"name":"","files":["lib.rs"]};
sourcesIndex["unicode_bidi"] = {"name":"","dirs":[{"name":"char_data","files":["mod.rs","tables.rs"]}],"files":["deprecated.rs","explicit.rs","format_chars.rs","implicit.rs","level.rs","lib.rs","prepare.rs"]};
sourcesIndex["unicode_normalization"] = {"name":"","files":["__test_api.rs","decompose.rs","lib.rs","lookups.rs","no_std_prelude.rs","normalize.rs","perfect_hash.rs","quick_check.rs","recompose.rs","replace.rs","stream_safe.rs","tables.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
sourcesIndex["url"] = {"name":"","files":["host.rs","lib.rs","origin.rs","parser.rs","path_segments.rs","quirks.rs","slicing.rs"]};
createSourceSidebar();
