name: build-musl

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: pull-all-the-source
      uses: actions/checkout@v2
      with:
        repository: .
        submodules: 'true'

    - name: setup-docker
      uses: docker-practice/actions-setup-docker@master
      with:
        docker_version: 19.03
        docker_channel: stable

    - name: musl-static-build
      run: |
        set -x
        docker run --name build-image \
            -v /home/runner/work/jsc-sys:/home/rust/jsc-sys \
            -v /home/runner/.cargo:/home/rust/.cargo \
            --pull \
            registry.gitlab.com/rust_musl_docker/image:stable-latest \
            /bin/bash -c "apt update && apt install -y ninja-build && \
                            cd /home/rust/jsc-sys && \
                            cargo build -vv --target=x86_64-unknown-linux-musl"

        echo "Build complete"
        docker cp build-image:/home/rust/jsc-sys/**/target/x86_64-unknown-linux-musl/debug/build/jscjs-sys-*/out/build/bin/jsc /home/runner/work/jsc"

        docker rm build-image
        docker rmi registry.gitlab.com/rust_musl_docker/image
        tar zcvf /home/runner/x86_64-unknown-linux-musl_debug-build.tar.gz /home/rust/jsc-sys/target/x86_64-unknown-linux-musl/debug/build/jscjs-sys-*/out/*
