name: build-linux

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: pull-all-the-source
      uses: actions/checkout@v2
      with:
        repository: '${{ github.repository }}'
        submodules: 'true'

    - name: install-ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: build-statically-linked-to-musl-libc
      uses: stevenleadbeater/rust-musl-builder@master
      with:
        args: /bin/bash -c "cargo build -vv --target=x86_64-unknown-linux-musl"
