name: Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: '${{ github.repository }}'
        submodules: 'true'
    - name: Build
      run: cargo build -vv
    
  build-darwin:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: '${{ github.repository }}'
        submodules: 'true'
    - name: Build
      run: cargo build -vv
