name: publish-docs
on:
  push:
  pull_request:
    branches:
      - master

jobs: 
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: pull-target-source
      uses: actions/checkout@v2
      with:
        repository: '${{ github.repository }}'
        submodules: 'true'
        fetch-depth: 1

    - name: install-gtk-deps
      run: |
        sudo apt update
        sudo apt install -y \
          autoconf automake autopoint autotools-dev cmake make gperf gobject-introspection \
          bubblewrap python3-dev python3-setuptools xdg-dbus-proxy python3-secretstorage \
          libasound2-dev \
          libatk1.0-dev \
          libedit-dev \
          libenchant-dev \
          libevent-dev \
          libfaad-dev \
          libffi-dev \
          libgcrypt20-dev \
          libgirepository1.0-dev \
          libgtk-3-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-bad1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgudev-1.0-dev \
          libhyphen-dev \
          libjpeg-dev \
          libmount-dev \
          libmpg123-dev \
          libnotify-dev \
          libopenjp2-7-dev \
          libopus-dev \
          libpango1.0-dev \
          libpng-dev \
          libpulse-dev \
          librsvg2-dev \
          libseccomp-dev \
          libsecret-1-dev \
          libsoup2.4-dev \
          libsqlite3-dev \
          libsrtp2-dev \
          libtasn1-6-dev \
          libvpx-dev \
          libupower-glib-dev \
          libwebp-dev \
          libwoff-dev \
          libxcomposite-dev \
          libxt-dev \
          libxtst-dev libxslt1-dev \
          libwayland-dev \
          llvm-12-dev \
          ninja-build
        sudo apt clean
      
    - name: build-docs
      run: cargo doc

    - name: configure-and-push-docs
      env:
        GITHUB_BRANCH: 'gh-pages'
        GITHUB_ACTOR: 'drtychai'
        GITHUB_TOKEN: '${{ secrets.GIT_DEPLOY_KEY }}'
        GITHUB_REPOSITORY: '${{ github.repository }}'
        CARGO_MANIFEST_DIR: '/home/runner/work/jsc-sys/jsc-sys'
        GHP_DOC_DIR: '/home/runner/work/jsc-sys/ghp'
      run: |
        cd target/doc \
          && git init \
          && git branch -m "${GITHUB_BRANCH}" \
          && git config user.name "${GITHUB_ACTOR}" \
          && git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" \
          && git remote add origin "git@github.com:${GITHUB_REPOSITORY}" \
          && git config core.sshCommand "ssh -i ${GITHUB_TOKEN}"
        git add ./* \
          && git commit -m "Crate Docs via CI" \
          && git push --force origin gh-pages 
