name: gnu

on:
  push:
    branches:
        - master
        - dev
  pull_request:
    branches:
        - master
        - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  build-gnu:
    runs-on: ubuntu-latest

    steps:
    - name: pull-all-source
      uses: actions/checkout@v2
      with:
        repository: '${{ github.repository }}'
        submodules: 'true'

    - name: install deps
      run: sudo apt install -y libgcrypt20-dev

    - name: build
      run: cargo build -vv --target=x86_64-unknown-linux-gnu
