name: gnu

on:
  push:
    branches:
        - master

  pull_request:
    branches:
        - master
        - staging
        - gnu

env:
  CARGO_TERM_COLOR: always

jobs:
  build-gnu:
    runs-on: ubuntu-20.04

    steps:
    - name: pull-all-source
      uses: actions/checkout@v2
      with:
        repository: '${{ github.repository }}'
        submodules: 'true'
        fetch-depth: 1

    - name: install-gtk-deps
      run: |
        sudo apt update
        sudo apt install -y \
          autoconf automake autopoint autotools-dev cmake make gperf gobject-introspection \
          bubblewrap python3-dev python3-setuptools xdg-dbus-proxy python3-secretstorage \
          libasound2-dev \
          libatk1.0-dev \
          libedit-dev \
          libenchant-dev \
          libevent-dev \
          libfaad-dev \
          libffi-dev \
          libgcrypt20-dev \
          libgirepository1.0-dev \
          libgtk-3-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-bad1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgudev-1.0-dev \
          libhyphen-dev \
          libjpeg-dev \
          libmount-dev \
          libmpg123-dev \
          libnotify-dev \
          libopenjp2-7-dev \
          libopus-dev \
          libpango1.0-dev \
          libpng-dev \
          libpulse-dev \
          librsvg2-dev \
          libseccomp-dev \
          libsecret-1-dev \
          libsoup2.4-dev \
          libsqlite3-dev \
          libsrtp2-dev \
          libtasn1-6-dev \
          libvpx-dev \
          libupower-glib-dev \
          libwebp-dev \
          libwoff-dev \
          libxcomposite-dev \
          libxt-dev \
          libxtst-dev libxslt1-dev \
          libwayland-dev \
          llvm-12-dev \
          ninja-build
        sudo apt clean

    - name: patch-cov
      run: git apply .github/workflows/sancov-remove.patch

    - name: build
      run: cargo build -vv --target=x86_64-unknown-linux-gnu

    - name: tests
      run: cargo test -vv
