name: gnu

on:
  push:
    branches:
        - master
        - dev
  pull_request:
    branches:
        - master
        - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  build-gnu:
    runs-on: ubuntu-20.04

    steps:
    - name: pull-all-source
      uses: actions/checkout@v2
      with:
        repository: '${{ github.repository }}'
        submodules: 'true'

    - name: install deps
      run: |
        sudo apt update --fix-missing
        sudo apt install -y -f
        echo y | sudo $( find ~ -path '*/gtk/install-dependencies' )

    - name: build
      run: cargo build -vv --target=x86_64-unknown-linux-gnu
